runtime: python312

instance_class: F1

entrypoint: streamlit run app.py --server.port 8080 --browser.serverAddress 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false

automatic_scaling:
  max_instances: 1

network:
  session_affinity: true
